'use strict';
const D=Impulso, KEY='impulso-v1', $=s=>document.querySelector(s), today=()=>D.day(new Date());
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={version:1,currency:'ARS',goals:[],records:{}}, storageError=false;
try { const saved=localStorage.getItem(KEY); if(saved)state=D.validate(JSON.parse(saved)); } catch(e) {storageError=true;}
let trendHidden=new Set();
let date=today(), week=D.monday(date), tab='hoy';
const presets=['30 minutos de lectura','2 sesiones de mindfulness','Contactar a un familiar o amigo','No fumar','No tomar alcohol','Sumar 30 puntos cardio','Dormir 8 horas','Tomar 2 litros de agua','Caminar 30 minutos','Escribir un diario'];
const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:state.currency,maximumFractionDigits:2}).format(n/100);
function save(){if(storageError){toast('Recuperá una copia válida antes de guardar cambios.');return false;}try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch(e){toast('No se pudo guardar. Exportá una copia antes de salir.');return false;}}
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4500);}
function modal(html){$('#modal').innerHTML='<div class="modal-top"><span class="eyebrow">IMPULSO · TU PROGRESO</span><button class="icon-button" onclick="closeModal()" aria-label="Cerrar">×</button></div>'+html;$('#modal').showModal();}
function closeModal(){$('#modal').close();}
function nice(d){return new Date(d+'T12:00:00').toLocaleDateString('es-AR',{day:'numeric',month:'long'});}
function empty(title,text){return `<div class="empty"><h3>${title}</h3><p>${text}</p><button class="button soft" onclick="goalForm()">＋ Elegir mi primer objetivo</button></div>`;}
function render(){
 tab=['hoy','ciclos','habitos','inspiracion','ajustes'].includes(location.hash.slice(1))?location.hash.slice(1):'hoy';
 $('#nav').innerHTML=[['hoy','◷','Mi día'],['ciclos','▤','Mis ciclos'],['habitos','✳','Hábitos'],['inspiracion','▷','Inspiración'],['ajustes','⚙','Ajustes']].map(([id,icon,label])=>`<a href="#${id}" class="${tab===id?'selected':''}" ${tab===id?'aria-current="page"':''}><span>${icon}</span>${label}</a>`).join('');
 $('#heading').textContent={hoy:'Cada día cuenta.',ciclos:'Tu semana, en perspectiva.',habitos:'Lo que repetís, crece.',inspiracion:'Un momento para vos.',ajustes:'A tu manera.'}[tab];
 $('#content').innerHTML=({hoy:dayView,ciclos:weekView,habitos:habitView,inspiracion:inspirationView,ajustes:settingsView}[tab])();
}
function dayView(){const m=D.daily(state,date),w=D.weekly(state,D.monday(date),today()),habits=D.habitGoals(state).filter(g=>D.habit(state,g,today()).earned).length;
 return `<section class="hero"><div><span class="eyebrow">${date===today()?'HOY ES UNA NUEVA OPORTUNIDAD':esc(nice(date).toUpperCase())}</span><h2 style="margin-top:12px">Construí la versión de vos que imaginás.</h2><p>Una decisión pequeña. Un paso más cerca.</p></div><div class="ring" style="--pct:${m.percent}%"><div class="ring-inner"><strong>${m.percent}%</strong><small>del día cumplido</small></div></div></section>${dailyQuoteCard()}<div class="stats"><div class="card"><small>OBJETIVOS CUMPLIDOS</small><div class="stat-value">${m.yes}<span style="color:#9aa58f;font-size:17px"> / ${m.total}</span></div><small>${m.pending} por registrar</small></div><div class="card"><small>BALANCE DEL CICLO</small><div class="stat-value">${money(w.balance)}</div><small>En ${state.currency} · lunes a domingo</small></div><div class="card"><small>HÁBITOS FORMADOS</small><div class="stat-value">${habits} <span style="color:#80a863">✳</span></div><small>Fruto de tu constancia</small></div></div><div class="section-head"><div><h2>Mis objetivos diarios</h2><p class="sub">✓ Lo cumplí &nbsp; · &nbsp; × No lo cumplí</p></div><div class="date-controls"><button class="icon-button" onclick="changeDay(-1)" aria-label="Día anterior">‹</button><input aria-label="Fecha del registro" type="date" value="${date}" max="${today()}" onchange="pickDay(this.value)"><button class="icon-button" onclick="changeDay(1)" ${date>=today()?'disabled':''} aria-label="Día siguiente">›</button></div></div>${D.goalsOn(state,date).map(g=>goalRow(g)).join('')||empty('Tu próximo hábito empieza acá.','Elegí un objetivo sugerido o creá uno propio para comenzar.')}<div class="close-day"><p>${m.pending?'Podés registrar cada resultado al final del día. Los pendientes no suman dinero y deben registrarse para completar el ciclo.':'Todos los resultados de este día están registrados. Podés corregirlos cuando lo necesites.'}</p><button class="button dark" onclick="closeDay()" ${!m.total||!m.pending?'disabled':''}>Cerrar día</button></div>`;
}
function goalRow(g){const v=D.status(state,g,date),h=D.habit(state,g,today());return `<article class="goal"><div class="goal-icon">${h.earned?'✳':'↗'}</div><div class="goal-body"><h3>${esc(g.title)}</h3><p>${g.reward||g.penalty?`+${money(g.reward)} / −${money(g.penalty)}`:'Tu bienestar también suma'} · ${h.earned?'Hábito formado':h.streak+'/3 ciclos personales'}</p></div><span class="badge">Diario</span><div class="actions"><button class="choice ${v===true?'yes':''}" onclick="mark('${g.id}',true)" aria-label="Cumplí: ${esc(g.title)}" aria-pressed="${v===true}">✓</button><button class="choice ${v===false?'no':''}" onclick="mark('${g.id}',false)" aria-label="No cumplí: ${esc(g.title)}" aria-pressed="${v===false}">×</button></div><button class="edit" onclick="goalForm('${g.id}')" aria-label="Editar ${esc(g.title)}">⋯</button></article>`;}
function mark(id,value){const before=D.graceEvents(state,today());state.records[date]??={};if(state.records[date][id]===value)delete state.records[date][id];else state.records[date][id]=value;const saved=save();render();if(saved)announceGrace(before);}
function pickDay(d){if(D.validDate(d)&&d<=today()){date=d;render();}}
function changeDay(n){pickDay(D.add(date,n));}
function closeDay(){const m=D.daily(state,date);modal(`<h2>Cerrar el ${nice(date)}</h2><p>Hay ${m.pending} objetivos sin registrar. Al cerrar, se marcarán como no cumplidos y se descontará el importe configurado para cada uno.</p><p class="sub">Podés corregir los resultados después.</p><div class="form-footer"><button class="button" onclick="closeModal()">Seguir registrando</button><button class="button dark" onclick="confirmClose()">Marcar pendientes y cerrar</button></div>`);}
function confirmClose(){const before=D.graceEvents(state,today());state.records[date]??={};D.goalsOn(state,date).forEach(g=>{if(D.status(state,g,date)===null)state.records[date][g.id]=false;});const saved=save();closeModal();render();toast('Día registrado. Mañana es otra oportunidad.');if(saved)announceGrace(before);}
function weekView(){const w=D.weekly(state,week,today());return `${goalTrendChart()}${weekdayChart()}<div class="section-head"><div><h2>${nice(week)} — ${nice(D.add(week,6))}</h2><p class="sub">Balance semanal de lunes a domingo · ${w.percent}% cumplido${D.add(week,6)>=today()?' hasta hoy':''}</p></div><div class="date-controls"><button class="icon-button" onclick="shiftWeek(-1)" aria-label="Semana anterior">‹</button><button class="button" onclick="week=D.monday(today());render()">Esta semana</button><button class="icon-button" onclick="shiftWeek(1)" ${week>=D.monday(today())?'disabled':''} aria-label="Semana siguiente">›</button></div></div><section class="hero"><div><span class="eyebrow">BALANCE PERSONAL · ${state.currency}</span><h2 style="margin-top:12px">${money(w.balance)}</h2><p>El valor de tus decisiones, día a día.</p></div><span style="font-size:65px;color:#80a863">↗</span></section><div class="week">${w.dates.map((d,i)=>`<div class="day"><small>${['LUN','MAR','MIÉ','JUE','VIE','SÁB','DOM'][i]} ${Number(d.slice(-2))}</small><strong>${d>today()?'—':D.daily(state,d).percent+'%'}</strong><small>${d>today()?'Próximo':D.daily(state,d).pending+' pend.'}</small></div>`).join('')}</div><div class="card" style="margin-top:24px"><h2>Tu balance, desglosado</h2><table class="ledger"><tr><td>Objetivos cumplidos</td><td class="positive">+${money(w.positive)}</td></tr><tr><td>Objetivos no cumplidos</td><td class="negative">−${money(w.negative)}</td></tr><tr><td>Premios por nuevos hábitos</td><td class="positive">+${money(w.bonus)}</td></tr><tr><td>Balance del ciclo</td><td>${money(w.balance)}</td></tr></table><p class="sub">Solo los resultados registrados modifican el balance. Los días pendientes cuentan como no cumplidos en el porcentaje, pero no generan descuentos automáticos.</p></div><p class="notice"><strong>Tu bienestar es el premio principal.</strong><br>El ahorro es un incentivo extra: lo que buscás cultivar es más energía para tu vida y confianza en vos.<br><br><strong>Dale un destino a tu esfuerzo.</strong><br>Elegí una meta concreta: tus próximas vacaciones, un curso o eso que hace tiempo querés comprar. Cada lunes, revisá el saldo positivo del ciclo anterior y, si está dentro de tus posibilidades, transferí ese monto a una billetera virtual o cuenta que reserves para esa meta. Así, tus hábitos también se convierten en ahorro para algo que te ilusiona.<br><br>Si el saldo es cero o negativo, esa semana no hay un monto sugerido para transferir: retomá tu meta en el próximo ciclo. Impulso registra tus incentivos; las transferencias las hacés vos y no se verifican en la app. Cada premio por hábito se cuenta una sola vez y se asigna a la semana de lunes a domingo en la que termina el tercer ciclo personal válido, una vez confirmado.</p>`;}
function shiftWeek(n){const next=D.add(week,n*7);if(next<=D.monday(today())){week=next;render();}}
function habitView(){return `<section class="hero"><div><span class="eyebrow">LA CONSTANCIA TIENE SU PREMIO</span><h2 style="margin-top:12px">3 ciclos a tu ritmo.<br>Con espacio para retomar.</h2><p>Tres ciclos consecutivos de siete días desde que empezás, con un día de margen por ciclo.</p></div><span style="font-size:70px;color:#719953">✳</span></section><p class="notice">Esta es la regla de progreso de la app, no una garantía de automatización del hábito. Cada objetivo empieza a contar desde su fecha de inicio, cualquier día de la semana. Si empezás un miércoles, tus ciclos van de miércoles a martes. Para formar el hábito necesitás tres ciclos completos consecutivos. Cada ciclo admite un día no cumplido si retomás al día siguiente. Dos fallos en un ciclo, no retomar al día siguiente o dejar días pasados sin registrar interrumpen la racha; los próximos ciclos conservan el día de inicio original. Si fallás el último día de un ciclo, queda en espera hasta que registres el día siguiente como cumplido. El margen no cambia los porcentajes ni los descuentos.</p>${D.habitGoals(state).map(g=>{const h=D.habit(state,g,today());return `<article class="card habit-card"><div class="section-head" style="margin:0"><h3>${esc(g.title)}</h3><span class="badge">${h.earned?'✳ Formado':h.streak+'/3 ciclos'}</span></div><div class="progress">${[1,2,3].map(i=>`<span class="${h.earned||h.streak>=i?'filled':''}"></span>`).join('')}</div><p class="sub">${h.earned?'Logrado el '+nice(h.earned):'Cada ciclo se confirma al día siguiente de completar sus siete días.'}</p><p class="sub">Inicio: ${nice(g.start)} · ciclos de siete días desde esa fecha.</p>${graceStatus(g)}<p class="sub">Premio personal: <strong>${money(g.bonus)}</strong>${h.earned?' · incluido en el balance de su ciclo':''}</p></article>`;}).join('')||empty('Todavía hay mucho por descubrir.','Agregá tu primer objetivo y empezá a construir constancia.')}<section class="notice"><strong>El premio más valioso se vive.</strong><p>Más bienestar, energía para lo que te importa y confianza en vos. Los puntos y el ahorro acompañan; cuidarte es lo que les da sentido. Tu valor no depende de un porcentaje, y un tropiezo no borra lo que ya construiste.</p></section><p class="sub">Al corregir registros pasados se recalculan la racha, el reconocimiento y el premio. Un hábito formado permanece reconocido aunque haya fallos posteriores.</p>`;}
function settingsView(){return `<div class="settings"><div class="card"><h2>Tu configuración</h2><label>Moneda <select aria-label="Moneda" onchange="setCurrency(this.value)">${['ARS','USD','EUR','MXN','CLP','COP','UYU'].map(c=>`<option ${c===state.currency?'selected':''}>${c}</option>`).join('')}</select></label><p class="sub">Cambiar la moneda cambia la unidad de todos los importes; no hace conversión de divisas.</p></div><div class="card" style="margin-top:18px"><h2>Una copia de tu progreso</h2><p class="sub">Tus datos se guardan localmente. Copiá el respaldo a un lugar seguro para recuperarlos si cambiás de dispositivo o desinstalás la app.</p><div class="form-footer" style="justify-content:flex-start"><button class="button soft" onclick="backup()">Exportar copia</button><button class="button" onclick="restoreForm()">Importar copia</button></div></div><div class="card" style="margin-top:18px"><h2>Reglas claras</h2><p class="sub">Todos los objetivos son diarios. Podés sumar tantos como necesites. El porcentaje es objetivos cumplidos dividido por objetivos activos. Los importes se registran con dos decimales. Los hábitos avanzan en ciclos personales de siete días desde el inicio de cada objetivo. La contabilidad sigue de lunes a domingo; son dos calendarios independientes.</p><p class="sub">Los cambios de nombre, importes o premio crean una nueva versión desde mañana para conservar el historial; la nueva versión empieza su propia racha. Eliminar un objetivo lo oculta de Hábitos de inmediato y lo retira de los objetivos diarios desde mañana. Sus registros y balances anteriores se conservan.</p></div><section class="card" style="margin-top:18px"><h2>Acerca de Impulso</h2><p class="sub">Desarrollado por <strong>Ezequiel Krieger Marin</strong></p><p class="sub">Un día a la vez.</p></section></div>`;}
function setCurrency(v){state.currency=v;save();render();}
function goalForm(id){const g=state.goals.find(g=>g.id===id);modal(`<h2>${g?'Editar objetivo':'¿Qué querés cultivar?'}</h2>${!g?`<p class="sub">Empezá con una idea o escribí la tuya.</p><div class="presets">${presets.map((p,i)=>`<button class="preset" onclick="document.getElementById('title').value=presets[${i}]">${esc(p)}</button>`).join('')}</div>`:'<p class="notice">Los cambios se aplican desde mañana como un nuevo objetivo, con una nueva racha. El historial actual se conserva.</p>'}<form id="goal-form"><label class="form-label" for="title">Mi objetivo diario</label><input id="title" required maxlength="120" placeholder="Por ejemplo: leer 30 minutos" value="${esc(g?.title||'')}"><div class="fields"><div><label class="form-label" for="reward">Si cumplo, sumo (${state.currency})</label><input id="reward" type="number" min="0" max="10000000" step="0.01" value="${(g?.reward||0)/100}" required></div><div><label class="form-label" for="penalty">Si no cumplo, resto (${state.currency})</label><input id="penalty" type="number" min="0" max="10000000" step="0.01" value="${(g?.penalty||0)/100}" required></div></div><label class="form-label" for="bonus">Premio por formar el hábito (${state.currency})</label><input id="bonus" type="number" min="0" max="10000000" step="0.01" value="${(g?.bonus||0)/100}" required><p class="sub">Opcional: dejá los importes en 0 si este objetivo no lleva dinero.</p><div class="form-footer">${g?'<button type="button" class="button danger" id="archive">Eliminar</button>':''}<button type="submit" class="button dark">${g?'Guardar cambios':'Agregar objetivo'}</button></div></form>`);
 $('#goal-form').onsubmit=e=>{e.preventDefault();const title=$('#title').value.trim();if(!title)return;const amounts=['reward','penalty','bonus'].map(k=>Math.round(Number($('#'+k).value)*100));if(!amounts.every(n=>Number.isFinite(n)&&n>=0&&n<=1e9))return;const start=g?D.add(today(),1):today();if(g&&g.end){toast('Este objetivo ya está eliminado o reemplazado.');return;}if(g)g.end=start;state.goals.push({id:crypto.randomUUID(),title,start,reward:amounts[0],penalty:amounts[1],bonus:amounts[2]});save();closeModal();render();toast(g?'Cambios programados para mañana.':'Un nuevo paso. ¡Vamos!');};
 if(g)$('#archive').onclick=()=>{const oldEnd=g.end;const oldDeleted=g.deleted;g.deleted=true;if(!g.end)g.end=D.add(today(),1);if(!save()){g.end=oldEnd;g.deleted=oldDeleted;return;}closeModal();render();toast('Objetivo eliminado de Hábitos. Se retira de Mi día desde mañana; tu historial se conserva.');};
}
function backup(){modal('<h2>Guardá tu copia</h2><p class="sub">Seleccioná y copiá este texto completo. Guardalo en un archivo de texto personal.</p><textarea id="backup" aria-label="Copia de seguridad" readonly></textarea><div class="form-footer"><button class="button dark" onclick="document.getElementById(\'backup\').select()">Seleccionar todo</button></div>');$('#backup').value=JSON.stringify(state,null,2);}
function restoreForm(){modal('<h2>Recuperar tu progreso</h2><p class="notice">La importación reemplaza los datos actuales. Exportá primero una copia si querés conservarlos.</p><textarea id="restore" aria-label="Pegar copia de seguridad" placeholder="Pegá aquí tu copia de Impulso"></textarea><div class="form-footer"><button class="button" onclick="closeModal()">Cancelar</button><button class="button dark" onclick="restore()">Validar e importar</button></div>');}
function restore(){try{const text=$('#restore').value;if(text.length>5000000)throw Error('Copia demasiado grande.');const next=D.validate(JSON.parse(text));if(next.goals.some(g=>g.start>D.add(today(),1))||Object.keys(next.records).some(d=>d>today()))throw Error('La copia contiene fechas futuras no válidas.');localStorage.setItem(KEY,JSON.stringify(next));state=next;storageError=false;$('#add').disabled=false;closeModal();render();toast('Tu progreso fue recuperado.');}catch(e){toast('No se importó la copia: '+e.message);}}
$('#add').onclick=()=>goalForm();window.addEventListener('hashchange',render);render();if(storageError){modal('<h2>No se pudo leer el progreso guardado</h2><p>La copia local tiene un formato no válido. Para evitar sobrescribirla, recuperá una copia válida desde Ajustes antes de continuar.</p>');$('#add').disabled=true;}

function graceStatus(g){
 const events=D.graceEvents(state,today()).filter(e=>e.id===g.id);
 const last=events[events.length-1];
 if(!last)return '<p class="sub">Un día de margen por ciclo personal de siete días, si retomás al día siguiente.</p>';
 return '<p class="notice">'+(last.kind==='pending'?'Tu avance está en espera: retomá el día siguiente al '+nice(last.date)+' para conservarlo.':'Margen confirmado el '+nice(last.date)+': retomaste al día siguiente y conservaste tu avance.')+'</p>';
}
function announceGrace(before){
 const keys=new Set(before.map(e=>e.id+':'+e.date+':'+e.kind));
 const changes=D.graceEvents(state,today()).filter(e=>!keys.has(e.id+':'+e.date+':'+e.kind));
 if(!changes.length)return;
 const lines=changes.map(e=>e.title+': '+(e.kind==='pending'?'tenés un día de margen en este ciclo personal. Cumplí al día siguiente para conservar tu avance.':'retomaste al día siguiente. Tu margen quedó confirmado y tu avance continúa.'));
 toast(lines.join(' '));
 if(window.ImpulsoReminders && typeof window.ImpulsoReminders.grace==='function') {
   changes.forEach((e,i)=>window.ImpulsoReminders.grace(e.id+':'+e.date+':'+e.kind,lines[i]));
 }
}

function dailyQuoteCard(){const q=ImpulsoDailyQuotes.get(today());return '<section class="daily-quote" aria-label="Frase del día"><span class="eyebrow">TU IMPULSO DE HOY</span><blockquote>«'+esc(q.text)+'»</blockquote><p class="quote-author">'+esc(q.author)+'</p><details><summary>Acerca de esta frase</summary><p>'+esc(q.note)+'</p></details></section>';}
let quoteRenderedDay=today();
function refreshDailyQuote(){if(quoteRenderedDay!==today()&&!$('#modal').open){const wasToday=date===quoteRenderedDay;quoteRenderedDay=today();if(wasToday)date=today();render();}}
window.addEventListener('focus',refreshDailyQuote);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshDailyQuote();});
setInterval(refreshDailyQuote,60000);

function weekdayChart(){
 const rows=D.weekdayProgress(state,today()),names=['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'];
 const fmt=v=>v===null?'—':v+'%';
 const grid=[0,25,50,75,100].map(v=>'<line x1="42" y1="'+(190-v*1.4)+'" x2="550" y2="'+(190-v*1.4)+'" stroke="#dce4d3"/><text x="34" y="'+(194-v*1.4)+'" text-anchor="end" font-size="11" fill="#526d46">'+v+'%</text>').join('');
 const bars=rows.map((r,i)=>{const x=62+i*70;return [r.history,r.current].map((v,j)=>v===null?'':'<rect x="'+(x+j*23)+'" y="'+(190-v*1.4)+'" width="18" height="'+Math.max(v*1.4,2)+'" rx="3" fill="'+(j?'#244b3b':'#aac88a')+'"/><text x="'+(x+j*23+9)+'" y="'+(182-v*1.4)+'" text-anchor="middle" font-size="11" fill="#244b3b">'+v+'</text>').join('')+'<text x="'+(x+20)+'" y="214" text-anchor="middle" font-size="13" fill="#244b3b">'+names[i]+'</text>';}).join('');
 return '<section class="card weekday-chart"><h2>Tu ritmo durante la semana</h2><p class="sub">Promedio histórico vs. semana actual · '+nice(D.monday(today()))+' al '+nice(D.add(D.monday(today()),6))+'</p><div class="chart-legend"><span><i style="background:#aac88a"></i>Promedio histórico</span><span><i style="background:#244b3b"></i>Semana actual</span></div><div class="chart-scroll"><svg viewBox="0 0 570 235" role="img" aria-label="Comparación de cumplimiento de lunes a domingo; valores exactos en la tabla de detalles">'+grid+bars+'</svg></div>'+(rows.every(r=>r.history===null)?'<p class="notice">Todavía no hay días anteriores a esta semana con objetivos. El promedio histórico aparecerá a partir de la próxima semana.</p>':'')+'<details><summary>Ver valores y cómo se calcula</summary><div class="chart-scroll"><table class="ledger"><thead><tr><th>Día</th><th>Histórico</th><th>Días comparados</th><th>Semana actual</th></tr></thead><tbody>'+rows.map((r,i)=>'<tr><td>'+names[i]+'</td><td>'+fmt(r.history)+'</td><td>'+r.count+'</td><td>'+fmt(r.current)+(r.date===today()?' · hoy, parcial':'')+(r.pending?' · '+r.pending+' pendientes':'')+'</td></tr>').join('')+'</tbody></table></div><p class="sub">Cada día pesa lo mismo: promediamos sus porcentajes de cumplimiento, con los objetivos que estaban activos en esa fecha. El histórico excluye la semana actual y los días sin objetivos; conserva los objetivos eliminados que eran activos entonces. Los pendientes cuentan como no cumplidos, igual que en Mi día. Hoy es un resultado parcial. — indica un día futuro o sin objetivos/datos, no un 0 %. Este gráfico siempre muestra la semana actual, aunque navegues por balances anteriores. Se recalcula al corregir registros.</p></details></section>';
}


function toggleTrend(id,on){if(on)trendHidden.delete(id);else trendHidden.add(id);refreshTrends();}
function selectTrends(all){trendHidden=new Set(all?[]:state.goals.map(g=>g.id));refreshTrends();}
function refreshTrends(){const el=document.getElementById('goal-trends');if(el)el.outerHTML=goalTrendChart();}
function trendColor(id){let h=0;for(const c of id)h=(h*31+c.charCodeAt(0))>>>0;return 'hsl('+(h%360)+',60%,35%)';}
function goalTrendChart(){
 const series=D.goalWeekdayProgress(state,today()), visible=series.filter(g=>!trendHidden.has(g.id)), names=['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'];
 const x=i=>50+i*77,y=p=>200-p*1.65;
 let svg=[0,25,50,75,100].map(p=>'<line x1="45" x2="525" y1="'+y(p)+'" y2="'+y(p)+'" stroke="#dde5d7"/><text x="36" y="'+(y(p)+4)+'" text-anchor="end" font-size="12" fill="#526558">'+p+'%</text>').join('');
 svg+=names.map((n,i)=>'<text x="'+x(i)+'" y="226" text-anchor="middle" font-size="13" fill="#244b3b">'+n+'</text>').join('');
 visible.forEach(g=>{const color=trendColor(g.id);let prev=null;g.days.forEach((d,i)=>{if(d.percent===null){prev=null;return;}if(prev!==null)svg+='<line x1="'+x(prev)+'" y1="'+y(g.days[prev].percent)+'" x2="'+x(i)+'" y2="'+y(d.percent)+'" stroke="'+color+'" stroke-width="3"/>';svg+='<circle cx="'+x(i)+'" cy="'+y(d.percent)+'" r="5" fill="'+color+'" stroke="white" stroke-width="1.5"><title>'+esc(g.title)+' · '+names[i]+': '+d.percent+'% ('+d.yes+'/'+d.count+')</title></circle>';prev=i;});});
 return '<section id="goal-trends" class="card weekday-chart"><span class="eyebrow">CONOCÉ TUS PATRONES</span><h2>Tus objetivos, día a día</h2><p class="sub">Cada línea muestra el porcentaje histórico de cumplimiento de un objetivo. Elegí cuáles comparar.</p><div class="chart-scroll"><svg viewBox="-18 0 578 245" role="img" aria-label="Cumplimiento histórico por objetivo de lunes a domingo. Valores en la tabla debajo.">'+svg+'</svg></div>'+(!series.length?'<p class="notice">Agregá tu primer objetivo para empezar a construir tus tendencias.</p>':!visible.length?'<p class="notice">Seleccioná al menos un objetivo para ver su tendencia.</p>':visible.every(g=>g.days.every(d=>d.percent===null))?'<p class="notice">Todavía no hay datos anteriores a esta semana para estos objetivos. Aparecerán a partir de la próxima semana.</p>':'')+'<div class="trend-actions"><button class="button soft" onclick="selectTrends(true)">Mostrar todos</button><button class="button soft" onclick="selectTrends(false)">Ocultar todos</button></div><fieldset class="trend-legend"><legend>Objetivos · activá o desactivá las referencias</legend>'+series.map(g=>'<label><input type="checkbox" '+(!trendHidden.has(g.id)?'checked':'')+' data-goal="'+g.id+'" onchange="toggleTrend(this.dataset.goal,this.checked)"><i style="background:'+trendColor(g.id)+'"></i><span>'+esc(g.title)+(g.ended?' <small>(histórico)</small>':'')+'<small>Desde '+nice(g.start)+'</small></span></label>').join('')+'</fieldset><details><summary>Ver porcentajes y cómo se calculan</summary><div class="chart-scroll"><table class="ledger"><thead><tr><th>Objetivo</th>'+names.map(n=>'<th>'+n+'</th>').join('')+'</tr></thead><tbody>'+visible.map(g=>'<tr><th>'+esc(g.title)+'<small>Desde '+nice(g.start)+'</small></th>'+g.days.map(d=>'<td>'+(d.percent===null?'—':d.percent+'%<small>'+d.yes+' de '+d.count+' días</small>')+'</td>').join('')+'</tr>').join('')+'</tbody></table></div><p class="sub">Para cada objetivo y día de la semana, dividimos los días cumplidos por los días en que estuvo activo. El histórico excluye la semana actual; los pendientes pasados cuentan como no cumplidos. Por ejemplo, 3 lunes cumplidos de 4 equivalen al 75 %. — significa que aún no hay datos, no un 0 %. Los objetivos eliminados y las versiones anteriores se conservan como históricos. Ocultar una línea solo cambia este gráfico. Si varias líneas coinciden, podés aislarlas con las referencias. La comparación general con la semana actual sigue disponible debajo.</p></details></section>';
}

function inspirationView(){
 const items=[
 ['◉','PRESENCIA','Meditación mindfulness','Volvé al presente, a tu ritmo.','meditación mindfulness guiada en español','sage'],
 ['◷','10 MINUTOS','Una pausa consciente','Diez minutos para conectar con vos.','mindfulness 10 minutos en español','sage'],
 ['☀','AL DESPERTAR','Empezá tu día','Una meditación para acompañar tu mañana.','meditación al despertar para empezar tu día en español','sun'],
 ['≈','RESPIRACIÓN','Respirá y aflojá','Hacé espacio para una pausa tranquila.','respiración consciente guiada 5 minutos en español','sage'],
 ['♫','CALMA','Música para relajarte','Bajá el ritmo y disfrutá el momento.','música relajante instrumental','lavender'],
 ['☾','DESCANSO','Música para dormir','Sonidos suaves para cerrar el día.','música suave para dormir','lavender'],
 ['⌁','NATURALEZA','Un refugio de sonidos','Lluvia, bosque y un ratito de calma.','sonidos de la naturaleza lluvia bosque relajación','sage'],
 ['◎','CONCENTRACIÓN','Música para trabajar','Un fondo instrumental para enfocarte.','música instrumental para trabajar y concentrarse sin letra','sun'],
 ['▤','LECTURA','Acompañá tu lectura','Un ambiente tranquilo para tu próximo capítulo.','música tranquila para leer sin letra','sun'],
 ['✧','CIERRE DEL DÍA','Una pausa de gratitud','Terminá el día reconociendo lo que te hizo bien.','meditación guiada de gratitud en español','lavender']
 ];
 return '<section class="inspiration-intro"><span class="eyebrow">PEQUEÑAS PAUSAS, NUEVOS IMPULSOS</span><p>Elegí lo que necesitás hoy. Cada tarjeta abre una búsqueda en YouTube para que encuentres tu propia compañía.</p><span class="inspiration-note">▷ Búsquedas en YouTube · requieren conexión a Internet</span></section><div class="inspiration-grid">'+items.map(([icon,tag,title,description,query,tone])=>'<a class="inspiration-card '+tone+'" href="https://www.youtube.com/results?search_query='+encodeURIComponent(query)+'" aria-label="'+esc(title)+': buscar en YouTube"><div class="inspiration-card-top"><span class="inspiration-icon" aria-hidden="true">'+icon+'</span><span class="eyebrow">'+tag+'</span></div><h2>'+title+'</h2><p>'+description+'</p><span class="inspiration-link">Buscar en YouTube <span aria-hidden="true">↗</span></span></a>').join('')+'</div>';
}
